Custom colors proof of concept
TokTok/toxic pull request #166
Opened 2020-12-05 20:52 UTC by lilibyte

I dont know C but this would be nice. seems to work as a poc.

2020-12-05 20:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TokTok/toxic?pullRequest=166) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TokTok/toxic?pullRequest=166) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TokTok/toxic?pullRequest=166) it.</sub>

2020-12-05 21:37 UTC, JFreegman commented
Looks good! you'll need to run astyle on it before I can merge though. In Toxic's base dir, run: `astyle --options=astylerc src/*`

2020-12-05 22:26 UTC, JFreegman requested changes
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/toktok/toxic/166)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @lilibyte)

___
*[misc/toxic.conf.example, line 36 at r2](https://reviewable.io/reviews/toktok/toxic/166#-MNoy5bm9bSpffgfFxl4:-MNoy5bm9bSpffgfFxl5:b-dh0sww) ([raw file](https://github.com/toktok/toxic/blob/91beedf4a06076df0d662e8e6869c1d854c1dd2f/misc/toxic.conf.example#L36)):*
> ```
> 
>   // set foreground notify (and typing) color in chat status bar (black, white, red, green, blue, cyan, yellow, magenta)
>   color_bar_accent = "yellow";
> ```

`color_bar_accent` is listed twice.


<!-- Sent from Reviewable.io -->

2020-12-05 22:27 UTC, JFreegman commented
You'll also need to accept the license agreement before I can merge (click the `details` link beside the `license/cla` check)

2020-12-06 00:46 UTC, lilibyte reviewed
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/toktok/toxic/166)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @JFreegman and @lilibyte)



<!-- Sent from Reviewable.io -->

2020-12-06 00:47 UTC, lilibyte reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/toktok/toxic/166)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @JFreegman and @lilibyte)



<!-- Sent from Reviewable.io -->

2020-12-06 00:48 UTC, lilibyte reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/toxic/166)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[misc/toxic.conf.example, line 36 at r2](https://reviewable.io/reviews/toktok/toxic/166#-MNoy5bm9bSpffgfFxl4:-MNpWB-2EIof33el6jSP:b-kj4url) ([raw file](https://github.com/toktok/toxic/blob/91beedf4a06076df0d662e8e6869c1d854c1dd2f/misc/toxic.conf.example#L36)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

`color_bar_accent` is listed twice.
</blockquote></details>

Sorry, fixed and squashed


<!-- Sent from Reviewable.io -->

2020-12-06 01:33 UTC, JFreegman reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/toktok/toxic/166)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @JFreegman)



<!-- Sent from Reviewable.io -->

2020-12-06 01:34 UTC, JFreegman approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/toktok/toxic/166#-:-MNpfsSo3VQJ-KOQ0ytS:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @JFreegman)



<!-- Sent from Reviewable.io -->

2020-12-06 01:35 UTC, merged

2020-12-06 02:20 UTC, lilibyte commented
Cool, thanks! Do you mind PoC pulls like this? I might try to extend this and maybe add some more customization features but I don't trust my ability to write efficient C code.

2020-12-06 02:41 UTC, JFreegman commented
> Cool, thanks! Do you mind PoC pulls like this? I might try to extend this and maybe add some more customization features but I don't trust my ability to write efficient C code.

Improvements are always welcome. You don't need to be a C expert to contribute, that's what we have the reviews and checks for.